# 🧪 Data Preprocessing in Scikit-learn

## 🧹 Handling Missing Values

### ℹ️ Techniques to Handle Missing Data

Handling missing values is the process of identifying and addressing empty or null data points within a dataset. In real-world data, values are often missing due to human error, equipment failure, or privacy concerns.

Since most machine learning algorithms **cannot handle missing values natively**, we rely on techniques such as **imputation** to fill these gaps with estimated values. This allows models to process data effectively **without discarding valuable samples**.

### ⚙️ How It Works

Scikit-learn primarily provides the **`SimpleImputer`** class for basic imputation. The workflow follows the standard **fit–transform** pattern:

1️⃣ **Identification**
The imputer scans the dataset for a missing value placeholder (commonly `np.nan`).

2️⃣ **Calculation (Fit)**
During the `fit()` step, a statistic is computed for each feature based on the selected strategy:

* Mean
* Median
* Most frequent
* Constant value

3️⃣ **Application (Transform)**
All missing values are replaced with the computed statistic.

🔹 For more complex relationships, **`IterativeImputer`** can be used.

### 🔑 Key Parameters & Characteristics

* **strategy** – Method used to fill missing values
* **fill_value** – Custom value when using `constant`
* **missing_values** – Placeholder to detect missing entries
* **add_indicator** – Adds a binary feature indicating missingness

### ✅ Pros & Strengths

* Prevents loss of valuable data samples
* Maintains original dataset structure
* Computationally efficient and scalable
* Supports numerical and categorical features

### ⚠️ Cons & Limitations

* May introduce bias if strategy is poorly chosen
* Mean/median imputation can reduce variance
* Does not model feature correlations (except IterativeImputer)

### 🌍 Real‑World Use Cases

* Medical datasets with missing lab test results
* Financial data with incomplete transaction histories
* Survey data where participants skipped questions

### 💼 Common Interview Questions

**Q:** Why should you fit an imputer only on the training set?

**A:** To prevent data leakage and overly optimistic model performance.

### 💻 Code Example

In [1]:
from sklearn.impute import SimpleImputer
import numpy as np

X = [[1, 2], [np.nan, 3], [7, np.nan], [4, 6]]

imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

print('Imputed Data:', X_imputed)

Imputed Data: [[1.         2.        ]
 [4.         3.        ]
 [7.         3.66666667]
 [4.         6.        ]]


### 📌 Key Takeaways

* Always analyze missingness before imputation
* Median > Mean when outliers exist
* Pipelines help avoid data leakage

# 🚨 Handling Outliers

## ℹ️ Methods to Detect and Handle Outliers

Handling outliers is the process of identifying and managing data points that differ significantly from the majority of a dataset. These extreme values may result from measurement errors, experimental variability, or genuinely rare events.

### ⚙️ How It Works

Scikit-learn offers several techniques for outlier detection, with **Isolation Forest** being one of the most popular.

**Concept:**
* Randomly selects a feature
* Randomly selects a split value between min and max
* Repeats recursively to isolate points

**Key Idea:**
Outliers are isolated using **fewer splits (shorter path lengths)** because they are rare and far from dense regions.

### 🔑 Key Parameters & Characteristics

* **contamination** – Expected proportion of outliers
* **n_estimators** – Number of trees in the forest
* **max_samples** – Number of samples used to train each tree

### ✅ Pros & Strengths

* Improves model accuracy and stability
* Reduces overfitting to noise
* Helps detect data quality issues or meaningful anomalies

### ⚠️ Cons & Limitations

* Risk of losing valuable information if true anomalies are removed
* Outlier threshold selection can be subjective
* Some detection algorithms are computationally expensive for very large datasets

### 🌍 Real-World Use Cases

* Credit card fraud detection (outliers are the target)
* Sensor data cleaning for predictive maintenance
* Housing price preprocessing for regression

### 💼 Common Interview Questions

**Q:** What is the difference between an outlier and noise?

**Q:** Why is `RobustScaler` preferred when outliers exist?

**Q:** Should you always remove outliers from a dataset?

In [2]:
from sklearn.ensemble import IsolationForest
import numpy as np

X = np.array([[1.1], [1.3], [1.2], [1.4], [100.0]])

iso = IsolationForest(contamination=0.2, random_state=42)
y_pred = iso.fit_predict(X)

print(f'Predictions: {y_pred}')  # -1 = outlier, 1 = inlier

Predictions: [ 1  1  1  1 -1]


### 📌 Key Takeaways

* Not all outliers are errors
* Detect first, then decide to remove, cap, or transform
* Prefer robust methods when outliers are unavoidable

# 🔤 Encoding Categorical Variables

## ℹ️ Convert Categorical Data to Numerical

Encoding categorical variables is the process of converting qualitative (non-numeric) data—such as names, colors, countries, or job titles—into a numerical format. Most machine learning algorithms **cannot work directly with text**, so encoding is required.

### Ordinal Encoding

* Assigns integer values (0, 1, 2, …)
* Assumes an **ordered relationship** between categories
* Example order: `Low < Medium < High`

In [3]:
from sklearn.preprocessing import OrdinalEncoder

X = np.array([['Low'], ['Medium'], ['High']])

encoder = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
encoded_X = encoder.fit_transform(X)

print(encoded_X)

[[0.]
 [1.]
 [2.]]


### One-Hot Encoding

* Creates a **binary column for each category**
* Prevents false numerical relationships
* Best for **nominal categories**

In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

X = np.array([['Red'], ['Blue'], ['Green'], ['Blue']])

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_X = encoder.fit_transform(X)

print(encoded_X)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


### 🔑 Key Parameters & Characteristics

* **sparse_output** – Return dense or sparse matrix
* **handle_unknown** – Handle unseen categories in test data
* **drop** – Avoid dummy variable trap
* **categories** – Manually specify category order

### ✅ Pros & Strengths

* Enables ML algorithms to process categorical data
* Preserves qualitative information
* Fully compatible with scikit-learn Pipelines
* Standardized Transformer API

### ⚠️ Cons & Limitations

* One-Hot Encoding can dramatically increase dimensionality
* Ordinal Encoding may introduce false ranking if misused
* High-cardinality features increase memory usage
* Requires careful handling of unseen categories in production

### 🌍 Real-World Use Cases

* Housing price prediction using neighborhood names
* Email classification using sender domains
* Medical records with symptom labels
* Customer segmentation by job title or region

### 💼 Common Interview Questions

**Q:** When should you use One-Hot Encoding vs Ordinal Encoding?

**Q:** What is the Dummy Variable Trap?

**Q:** How does `OneHotEncoder` handle unseen categories?

### 📌 Key Takeaways

* Use **One-Hot** for nominal categories
* Use **Ordinal** only when order matters
* Always prepare for unseen categories

---

🚀 *Part of Scikit-learn Explorer*
Crafted with 💻 by **Ahmed Ashraf**